import { ArrowUpRight, ShieldCheck, Terminal, Search, Code2, Activity, Globe2, LockKeyhole, Cpu, FileText, ClipboardCheck, GraduationCap, Code2 as WebCode } from "lucide-react";
import { Reveal } from "@/components/reveal";

const skills = [
  { icon: Search, title: "OSINT", text: "Strukturierte Recherche, Quellenbewertung und technische Webanalyse." },
  { icon: ShieldCheck, title: "Web Security", text: "Security orientierte Analyse von Webanwendungen, APIs und Infrastruktur." },
  { icon: Terminal, title: "Linux", text: "Linux Workflows, Automatisierung, Netzwerk und Systemanalyse." },
  { icon: Code2, title: "Full Stack Development", text: "TypeScript, Next.js, React, Node.js und eigene Tools für Security und Analyse Workflows." },
  { icon: Cpu, title: "KI-Automatisierung", text: "KI-gestützte Automatisierung mit OpenAI und Anthropic sowie die Integration von LLMs in technische Workflows." },
];
const projects = [
  { name: "web-osint", text: "Technische Webanalyse und OSINT Workflows.", href: "https://github.com/linuxaaron/web-osint" },
  { name: "malware-analyzer", text: "Strukturierte Analyse verdächtiger Dateien.", href: "https://github.com/linuxaaron/malware-analyzer" },
];

export default function Home() {
  const jsonLd = { "@context": "https://schema.org", "@type": "Person", name: "Joscha Aaron Schmidt", jobTitle: "IT Specialist | Full Stack Developer | AI Automation | OSINT | Web Security | Cybersecurity | Linux", url: "https://www.joschaschmidt.com", sameAs: ["https://github.com/linuxaaron", "https://www.instagram.com/linux_aaron/", "https://www.tiktok.com/@linux_aaron/"] };
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <section className="grid-bg hero-glow relative overflow-hidden border-b border-[var(--border)]">
      <div className="container grid min-h-[calc(100vh-64px)] items-center gap-14 py-16 sm:py-20 lg:grid-cols-[1.25fr_.75fr] lg:py-28">
        <div className="max-w-4xl">
          <Reveal><p className="mb-5 font-mono text-xs tracking-[0.22em] text-[var(--accent)]">FULL STACK DEVELOPMENT · KI-AUTOMATISIERUNG · OSINT · WEB SECURITY · CYBERSECURITY · LINUX</p></Reveal>
          <Reveal delay={.05}><h1 className="text-5xl font-semibold tracking-[-0.055em] sm:text-7xl lg:text-8xl">Technische<br/><span className="text-[var(--muted)]">Analyse.</span></h1></Reveal>
          <Reveal delay={.1}><p className="mt-7 max-w-2xl text-base leading-7 text-[var(--muted)] sm:text-lg sm:leading-8">Ich entwickle Webanwendungen, automatisiere Prozesse mit KI, untersuche Systeme, recherchiere digitale Spuren und baue praktische Security Tools mit Fokus auf nachvollziehbare Ergebnisse.</p></Reveal>
          <Reveal delay={.15}><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a href="/projekte" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-medium !text-black transition hover:-translate-y-0.5 hover:bg-zinc-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-400">Projekte ansehen <ArrowUpRight size={16}/></a><a href="/buchung" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-[var(--accent)] px-5 py-3 text-sm font-medium text-black transition hover:-translate-y-0.5 hover:brightness-110 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-400"><ClipboardCheck size={16}/> Audit / Vortrag buchen</a><a href="/blog" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-[var(--accent)]/60 px-5 py-3 text-sm font-medium text-[var(--accent)] transition hover:-translate-y-0.5 hover:bg-[var(--accent)]/10 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-400"><FileText size={16}/> Security Blog</a><a href="/ueber-mich" className="inline-flex min-h-11 items-center justify-center rounded-full border border-[var(--border)] px-5 py-3 text-sm font-medium transition hover:-translate-y-0.5 hover:border-[var(--accent)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-400">Über mich</a></div></Reveal>
          <Reveal delay={.2}><div className="mt-11 grid max-w-xl grid-cols-3 gap-4 border-t border-[var(--border)] pt-6 sm:mt-14 sm:gap-6"><div><p className="font-mono text-xl font-semibold sm:text-2xl">Full Stack</p><p className="mt-1 text-xs text-[var(--muted)]">Development</p></div><div><p className="font-mono text-xl font-semibold sm:text-2xl">Web</p><p className="mt-1 text-xs text-[var(--muted)]">Security</p></div><div><p className="font-mono text-xl font-semibold sm:text-2xl">KI</p><p className="mt-1 text-xs text-[var(--muted)]">Automation</p></div></div></Reveal>
        </div>
        <Reveal delay={.12} className="hidden lg:block"><div className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)] shadow-2xl shadow-black/20"><div className="flex items-center gap-2 border-b border-[var(--border)] px-4 py-3"><span className="h-2 w-2 rounded-full bg-red-400/70"/><span className="h-2 w-2 rounded-full bg-yellow-400/70"/><span className="h-2 w-2 rounded-full bg-green-400/70"/><span className="ml-auto font-mono text-[10px] text-[var(--muted)]">analysis://local</span></div><div className="p-5 font-mono text-xs leading-7"><p className="text-[var(--muted)]">$ whoami</p><p className="text-[var(--accent)]">joscha@linux:~$ FULL STACK / AI / SECURITY</p><p className="mt-3 text-[var(--muted)]">$ scan --target web</p><div className="mt-2 space-y-1"><p><span className="text-[var(--accent)]">[OK]</span> surface mapped</p><p><span className="text-[var(--accent)]">[OK]</span> technologies identified</p><p><span className="text-[var(--accent)]">[OK]</span> public sources correlated</p><p><span className="text-[var(--accent)]">[OK]</span> AI context structured</p><p><span className="text-[var(--accent)]">[INFO]</span> report generated</p></div><p className="mt-3 text-[var(--muted)]">$ _</p></div></div></Reveal>
      </div>
    </section>
    <section className="border-b border-[var(--border)] bg-[color-mix(in_srgb,var(--surface)_55%,transparent)] py-20 sm:py-24"><div className="container"><Reveal><div className="mb-10"><p className="font-mono text-xs tracking-[0.2em] text-[var(--accent)]">01 / CAPABILITIES</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Kompetenzen</h2><p className="mt-4 max-w-2xl text-[var(--muted)]">Technische Fähigkeiten in Full Stack Development, KI-Automatisierung, OSINT, Web Security und Linux mit Fokus auf nachvollziehbare Methoden und saubere Ergebnisse.</p></div></Reveal><div className="grid gap-px overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--border)] md:grid-cols-2">{skills.map(({icon: Icon,title,text},i)=><Reveal key={title} delay={i*.05} className={i === skills.length - 1 ? "md:col-span-2" : undefined}><article className="group h-full bg-[var(--surface)] p-6 sm:p-7 transition hover:bg-[var(--surface-2)]"><Icon size={20} className="text-[var(--accent)] transition group-hover:scale-110"/><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{text}</p></article></Reveal>)}</div></div></section>
    <section id="webentwicklung" className="border-b border-[var(--border)] bg-[var(--section-warm)] py-20 sm:py-24"><div className="container"><Reveal><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-xs tracking-[0.2em] text-[var(--accent)]">02 / WEBENTWICKLUNG</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Professionelle Websites ohne unnötigen Agentur Overhead.</h2><p className="mt-4 max-w-2xl text-[var(--muted)]">Individuelle Landingpages und Business Websites mit responsive Design, Performance, SEO Basis und sicherem Deployment. Klare Leistungen, individuelle Angebote und eine direkte Abstimmung.</p></div><a href="/webentwicklung" className="inline-flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-full bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-black transition hover:-translate-y-0.5 hover:brightness-110">Webentwicklung ansehen <ArrowUpRight size={16}/></a></div></Reveal><div className="mt-10 grid gap-4 md:grid-cols-3"><Reveal><article className="h-full rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><WebCode className="text-[var(--accent)]" size={22}/><h3 className="mt-6 text-xl font-semibold">Landingpages</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Schnelle, responsive Seiten für Angebote, Produkte, Kampagnen und lokale Unternehmen.</p></article></Reveal><Reveal delay={.05}><article className="h-full rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><Globe2 className="text-[var(--accent)]" size={22}/><h3 className="mt-6 text-xl font-semibold">Business Websites</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Mehrseitige Websites mit klarer Struktur, Kontaktmöglichkeiten und professioneller Darstellung.</p></article></Reveal><Reveal delay={.1}><article className="h-full rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><ShieldCheck className="text-[var(--accent)]" size={22}/><h3 className="mt-6 text-xl font-semibold">Sicheres Deployment</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Performance, technische Basis SEO und sauberes Deployment auf moderner Infrastruktur.</p></article></Reveal></div></div></section>
    <section id="ki-automatisierung" className="border-b border-[var(--border)] bg-[color-mix(in_srgb,var(--surface)_55%,transparent)] py-20 sm:py-24"><div className="container"><Reveal><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-xs tracking-[0.2em] text-[var(--accent)]">03 / KI-AUTOMATISIERUNG</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">KI-gestützte Automatisierung &amp; Context Engineering.</h2><p className="mt-4 max-w-3xl text-[var(--muted)]">Ich entwickle und integriere KI-gestützte Systeme mit <strong className="text-[var(--text)]">OpenAI und Anthropic</strong>. Ein besonderer Schwerpunkt liegt auf der Kontexterstellung für KI-betriebene Systeme: Informationen, Wissensquellen, Prompts und Systemkontexte werden strukturiert, damit Modelle relevante Informationen zuverlässig verarbeiten und für ihre jeweiligen Aufgaben nutzen können.</p></div></div></Reveal><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Reveal><article className="h-full rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><Cpu className="text-[var(--accent)]" size={22}/><h3 className="mt-6 text-lg font-semibold">OpenAI &amp; Anthropic</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Integration moderner LLMs in Anwendungen, Automatisierungen und bestehende Workflows.</p></article></Reveal><Reveal delay={.05}><article className="h-full rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><Code2 className="text-[var(--accent)]" size={22}/><h3 className="mt-6 text-lg font-semibold">KI-Workflows</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">API-basierte Automatisierung und intelligente Prozessketten für wiederkehrende Aufgaben.</p></article></Reveal><Reveal delay={.1}><article className="h-full rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><FileText className="text-[var(--accent)]" size={22}/><h3 className="mt-6 text-lg font-semibold">Context Engineering</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Strukturierung von Kontext, Wissen und Systeminformationen für zuverlässigere KI-Ausgaben.</p></article></Reveal><Reveal delay={.15}><article className="h-full rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><Search className="text-[var(--accent)]" size={22}/><h3 className="mt-6 text-lg font-semibold">Knowledge Context</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Aufbereitung und Einbindung relevanter Wissensquellen in KI-betriebene Systeme.</p></article></Reveal></div></div></section>
    <section className="border-b border-[var(--border)] bg-[color-mix(in_srgb,var(--surface-2)_45%,transparent)] py-20 sm:py-24"><div className="container"><Reveal><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-xs tracking-[0.2em] text-[var(--accent)]">04 / SERVICES</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Security Audits &amp; Fachvorträge</h2><p className="mt-4 max-w-2xl text-[var(--muted)]">Technische Prüfungen und praxisnahe Wissensvermittlung für Unternehmen, Bildungseinrichtungen und IT Teams.</p></div><a href="/buchung" className="inline-flex items-center gap-2 text-sm font-medium text-[var(--accent)]">Anfrage starten <ArrowUpRight size={15}/></a></div></Reveal><div className="mt-10 grid gap-4 lg:grid-cols-2"><Reveal><a href="/buchung" className="group no-liquid block rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-7"><ClipboardCheck className="text-[var(--accent)]" size={22}/><h3 className="mt-7 text-2xl font-semibold">Technische Security Audits</h3><p className="mt-3 leading-7 text-[var(--muted)]">Web Security, OSINT, Angriffsflächen und technische Reviews innerhalb eines klar definierten Scopes.</p><span className="mt-6 inline-flex items-center gap-2 text-sm text-[var(--accent)]">Audit anfragen <ArrowUpRight size={15}/></span></a></Reveal><Reveal delay={.06}><a href="/buchung" className="group block rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-7 transition hover:-translate-y-1 hover:border-[var(--accent)]"><GraduationCap className="text-[var(--accent)]" size={22}/><h3 className="mt-7 text-2xl font-semibold">Vorträge &amp; Schulungen</h3><p className="mt-3 leading-7 text-[var(--muted)]">OSINT, Web Security, Linux, Cybersecurity und Incident Response individuell für Zielgruppe und Format.</p><span className="mt-6 inline-flex items-center gap-2 text-sm text-[var(--accent)]">Vortrag anfragen <ArrowUpRight size={15}/></span></a></Reveal></div></div></section>
    <section className="border-b border-[var(--border)] bg-[color-mix(in_srgb,var(--surface-2)_45%,transparent)] py-20 sm:py-24"><div className="container"><Reveal><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-xs tracking-[0.2em] text-[var(--accent)]">05 / KNOWLEDGE BASE</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Security Blog</h2><p className="mt-4 max-w-2xl text-[var(--muted)]">Praxisnahe technische Beiträge zu Linux, Cybersecurity, OSINT und Incident Response.</p></div><a href="/blog" className="inline-flex items-center gap-2 text-sm font-medium text-[var(--accent)]">Alle Beiträge <ArrowUpRight size={15}/></a></div></Reveal><div className="mt-10 grid gap-4 lg:grid-cols-2"><Reveal><a href="/blog/essential-linux-commands-cybersecurity" className="group block rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 transition duration-300 hover:-translate-y-1 hover:border-[var(--accent)]"><div className="mb-8 flex items-center justify-between"><span className="font-mono text-xs text-[var(--accent)]">FEATURED · DE</span><FileText size={18} className="text-[var(--muted)] transition group-hover:text-[var(--accent)]"/></div><h3 className="text-xl font-semibold">Linux für Cybersecurity: Befehle, Analyse &amp; Incident Response</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Netzwerkdiagnose, Prozessanalyse, Forensik, Log Analyse, Hardening und strukturierte Incident Response Triage.</p><span className="mt-6 inline-flex items-center gap-2 text-sm text-[var(--accent)]">Artikel lesen <ArrowUpRight size={15}/></span></a></Reveal><Reveal delay={.06}><a href="/blog" className="group block rounded-2xl border border-dashed border-[var(--border)] bg-[var(--surface)]/60 p-6 transition duration-300 hover:border-[var(--accent)]"><div className="mb-8 font-mono text-xs text-[var(--muted)]">MORE ARTICLES</div><h3 className="text-xl font-semibold">Weitere Security Themen</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Weitere Beiträge und technische Analysen werden hier gesammelt und nach Themen sortiert.</p><span className="mt-6 inline-flex items-center gap-2 text-sm text-[var(--accent)]">Blog öffnen <ArrowUpRight size={15}/></span></a></Reveal></div></div></section>
    <section className="border-b border-[var(--border)] py-20 sm:py-24"><div className="container"><Reveal><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-xs tracking-[0.2em] text-[var(--accent)]">06 / SELECTED WORK</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Aktuelle Projekte</h2></div><a href="/projekte" className="inline-flex items-center gap-2 text-sm font-medium">Alle Projekte <ArrowUpRight size={15}/></a></div></Reveal><div className="mt-10 grid gap-4 lg:grid-cols-2">{projects.map((p,i)=><Reveal key={p.name} delay={i*.06}><a href={p.href} target="_blank" rel="noreferrer" className="group block rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 transition duration-300 hover:-translate-y-1 hover:border-[var(--accent)]"><div className="mb-10 flex items-center justify-between"><span className="font-mono text-xs text-[var(--muted)]">0{i+1}</span><ArrowUpRight size={17} className="text-[var(--muted)] transition group-hover:text-[var(--accent)]"/></div><h3 className="text-xl font-semibold">{p.name}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{p.text}</p></a></Reveal>)}</div></div></section>
    <section className="py-20 sm:py-24"><div className="container"><Reveal><div className="grid gap-4 sm:grid-cols-4"><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><Activity className="text-[var(--accent)]" size={19}/><p className="mt-8 font-semibold">Research</p><p className="mt-1 text-xs text-[var(--muted)]">Quellen & Korrelation</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><Globe2 className="text-[var(--accent)]" size={19}/><p className="mt-8 font-semibold">Web Analysis</p><p className="mt-1 text-xs text-[var(--muted)]">Surface & Stack</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><LockKeyhole className="text-[var(--accent)]" size={19}/><p className="mt-8 font-semibold">Security</p><p className="mt-1 text-xs text-[var(--muted)]">Defensive mindset</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><Cpu className="text-[var(--accent)]" size={19}/><p className="mt-8 font-semibold">Open Source</p><p className="mt-1 text-xs text-[var(--muted)]">Eigene Projekte</p></div></div></Reveal></div></section>
  </main>;
}
