import { ArrowUpRight, Bot, Braces, FileSearch, Globe2, ShieldCheck, Terminal } from "lucide-react";
import { Reveal } from "@/components/reveal";
import styles from "./home.module.css";

const disciplines = [
  { code: "01", icon: Globe2, title: "Webentwicklung", text: "Websites und Anwendungen mit klarer Informationsarchitektur, sauberem Deployment und einer belastbaren technischen Basis.", href: "/webentwicklung" },
  { code: "02", icon: ShieldCheck, title: "Web Security", text: "Fokussierte technische Reviews von Angriffsflächen, Konfigurationen und nachvollziehbaren Maßnahmen.", href: "/buchung" },
  { code: "03", icon: Bot, title: "KI-Automatisierung", text: "KI-gestützte Workflows und strukturierter Kontext für zuverlässige technische Automatisierung.", href: "/projekte" },
  { code: "04", icon: FileSearch, title: "OSINT & Analyse", text: "Digitale Spuren, offene Quellen und technische Indikatoren strukturiert bewerten und einordnen.", href: "/projekte" },
];
const projects = [
  { label: "OPEN SOURCE", name: "web-osint", text: "Technische Webanalyse und OSINT-Workflows.", href: "https://github.com/linuxaaron/web-osint" },
  { label: "OPEN SOURCE", name: "malware-analyzer", text: "Strukturierte Analyse verdächtiger Dateien.", href: "https://github.com/linuxaaron/malware-analyzer" },
];

export default function Home() {
  const jsonLd = { "@context": "https://schema.org", "@type": "Person", name: "Joscha Aaron Schmidt", jobTitle: "IT Specialist | Full Stack Developer | AI Automation | OSINT | Web Security | Cybersecurity | Linux", url: "https://www.joschaschmidt.com", sameAs: ["https://github.com/linuxaaron", "https://www.instagram.com/linux_aaron/", "https://www.tiktok.com/@linux_aaron/"] };
  return <main className={styles.home}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <section className={styles.hero} aria-labelledby="hero-title"><div className={styles.heroGrid} aria-hidden="true" /><div className={`container ${styles.heroContent}`}><div className={styles.heroCopy}><Reveal><p className={styles.eyebrow}><span /> INDEPENDENT TECHNICAL PRACTICE</p></Reveal><Reveal delay={0.05}><h1 id="hero-title">Technik, die<br /><em>prüfbar</em> bleibt.</h1></Reveal><Reveal delay={0.1}><p className={styles.lede}>Webentwicklung, Security, KI-Automatisierung und OSINT für Vorhaben, bei denen ein funktionierendes Ergebnis allein nicht genügt. Ich mache technische Entscheidungen nachvollziehbar.</p></Reveal><Reveal delay={0.15}><div className={styles.actions}><a href="/buchung" className={styles.primaryAction}>Projekt besprechen <ArrowUpRight size={17} /></a><a href="/projekte" className={styles.textAction}>Arbeiten ansehen <span>→</span></a></div></Reveal></div><Reveal delay={0.12} className={styles.mapReveal}><aside className={styles.evidenceMap} aria-label="Arbeitsfelder"><div className={styles.mapTopline}><span>FIELD NOTE / 001</span><span>DE · REMOTE</span></div><div className={styles.mapBody}><p className={styles.mapTitle}>Was wird<br />sichtbar?</p><div className={`${styles.node} ${styles.nodeOne}`}><Terminal size={15} /><span>Systeme<br />verstehen</span></div><div className={`${styles.node} ${styles.nodeTwo}`}><ShieldCheck size={15} /><span>Risiken<br />einordnen</span></div><div className={`${styles.node} ${styles.nodeThree}`}><Braces size={15} /><span>Lösungen<br />bauen</span></div><i className={`${styles.connector} ${styles.connectorOne}`} /><i className={`${styles.connector} ${styles.connectorTwo}`} /><i className={`${styles.connector} ${styles.connectorThree}`} /><div className={styles.mapCore}>SCOPE<br /><strong>01</strong></div></div><div className={styles.mapLegend}><span><b /> ANALYSE</span><span><b /> UMSETZUNG</span><span><b /> DOKUMENTATION</span></div></aside></Reveal></div><div className={`container ${styles.proofLine}`}><span>FULL STACK DEVELOPMENT</span><span>WEB SECURITY</span><span>KI-AUTOMATISIERUNG</span><span>OSINT</span><span>LINUX SYSTEMS</span></div></section>
    <section className={styles.intro} aria-labelledby="approach-title"><div className={`container ${styles.introGrid}`}><Reveal><p className={styles.sectionLabel}>ARBEITSWEISE <span>— 01</span></p></Reveal><div><Reveal><h2 id="approach-title">Klarer Scope.<br />Saubere Übergabe.</h2></Reveal><Reveal delay={0.05}><p className={styles.introText}>Ob Website, Security-Review oder Recherche: Am Anfang steht die Fragestellung, nicht ein Standardpaket. Ergebnis und Grenzen des Scopes werden so dokumentiert, dass Entscheidungen darauf aufbauen können.</p></Reveal><Reveal delay={0.1}><a href="/ueber-mich" className={styles.inlineLink}>Über die Arbeitsweise <ArrowUpRight size={16} /></a></Reveal></div></div></section>
    <section className={styles.disciplineSection} aria-labelledby="disciplines-title"><div className={`container ${styles.sectionHead}`}><Reveal><p className={styles.sectionLabel}>LEISTUNGEN <span>— 02</span></p></Reveal><Reveal delay={0.04}><h2 id="disciplines-title">Vier Felder.<br />Ein technischer Blick.</h2></Reveal></div><div className={`container ${styles.disciplines}`}>{disciplines.map(({ code, icon: Icon, title, text, href }, index) => <Reveal key={title} delay={index * 0.06}><a href={href} className={styles.discipline}><div className={styles.disciplineMeta}><span>{code}</span><Icon size={20} /></div><h3>{title}</h3><p>{text}</p><span className={styles.disciplineArrow}>Details <ArrowUpRight size={16} /></span></a></Reveal>)}</div></section>
    <section className={styles.workSection} aria-labelledby="work-title"><div className={`container ${styles.workGrid}`}><div><Reveal><p className={styles.sectionLabel}>AUSWAHL <span>— 03</span></p></Reveal><Reveal delay={0.05}><h2 id="work-title">Werkzeuge sind<br />Teil der Arbeit.</h2></Reveal><Reveal delay={0.1}><p className={styles.workText}>Eigene Open-Source-Projekte machen Methoden, technische Interessen und Entwicklungsarbeit konkret sichtbar.</p></Reveal></div><div className={styles.projectList}>{projects.map((project, index) => <Reveal key={project.name} delay={0.1 + index * 0.06}><a href={project.href} target="_blank" rel="noreferrer" className={styles.project}><div><p>{project.label}</p><h3>{project.name}</h3><span>{project.text}</span></div><ArrowUpRight size={20} /></a></Reveal>)}<Reveal delay={0.24}><a href="/projekte" className={styles.allProjects}>Alle Projekte <ArrowUpRight size={16} /></a></Reveal></div></div></section>
    <section className={styles.cta} aria-labelledby="contact-title"><div className={`container ${styles.ctaInner}`}><Reveal><p className={styles.sectionLabel}>KONTAKT <span>— 04</span></p></Reveal><Reveal delay={0.05}><h2 id="contact-title">Eine technische Frage<br />ist ein guter Anfang.</h2></Reveal><Reveal delay={0.1}><a href="/buchung" className={styles.ctaButton}>Anfrage starten <ArrowUpRight size={18} /></a></Reveal></div></section>
  </main>;
}
